# Generated by Django 3.2.4 on 2021-06-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_login_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='firstname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='lastname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
